#define MATERIAL_LEVEL_HOLOGRAM = 0
#define MATERIAL_LEVEL_FRAME = 1
#define MATERIAL_LEVEL_WOOD = 2
#define MATERIAL_LEVEL_METAL = 3
#define MATERIAL_LEVEL_REINFORCED = 4

#define PLACEMENT_MODE_NONE = 0
#define PLACEMENT_MODE_FREE = 1
#define PLACEMENT_MODE_SNAP = 2
#define PLACEMENT_MODE_BOTH = 3

#define SNAP_ALIGN_NONE = 0
#define SNAP_ALIGN_UP = 1
#define SNAP_ALIGN_FORWARD = 2